services:
 mongo-cars:
  image: mongo:latest
  ports:
    - 27017:27017
  volumes:
    - mongodb_car_data:/data/db
    
 mysql-driver:
  image: mysql:latest
  ports:
    - 3306:3306
  volumes:
    - mysql_driver_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 mysql-tour:
  image: mysql:latest
  ports:
    - 3307:3306
  volumes:
    - mysql_tour_data:/var/lib/mysql
  environment:
   MYSQL_ROOT_PASSWORD: abc123
    
 car-service:
  depends_on:
    - mongo-cars
  image: timofaes/car-service:latest
  ports:
    - 8080:8080
  links:
    - mongo-cars
  environment:
   MONGODB_PORT: 27017
   MONGODB_HOST: mongo-cars
   
 tour-service:
  depends_on:
    - mysql-tour
  image: timofaes/tour-service:latest
  ports:
    - 8081:8081
  links:
    - mysql-tour
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-tour
   MYSQL_DB_PORT: 3306

 driver-service:
  image: timofaes/driver-service
  ports:
    - 8082:8082
  environment:
   MYSQL_DB_USERNAME: root
   MYSQL_DB_PASSWORD: abc123
   MYSQL_DB_HOST: mysql-driver
   MYSQL_DB_PORT: 3306

 api-gateway:
   depends_on:
     - driver-service
     - car-service
     - tour-service
   image: timofaes/gateway
   ports:
     - 8083:8083
   links:
     - driver-service
     - car-service
     - tour-service
   environment:
     DRIVER_SERVICE_BASEURL: http://driver-service:8082
     CAR_SERVICE_BASEURL: http://car-service:8080
     TOUR_SERVICE_BASEURL: http://tour-service:8081

volumes:
 mongodb_car_data:
 mysql_driver_data:
 mysql_tour_data: