server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
        - id: car-service-all
          uri: ${CAR_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/car
            - Method=GET,OPTIONS
          filters:
            - SetPath=/api/car/all
        - id: car-service-post
          uri: ${CAR_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/car
            - Method=POST,OPTIONS
          filters:
            - SetPath=/api/car
        - id: car-service-post
          uri: ${CAR_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/car/{id}
            - Method=PUT,OPTIONS
          filters:
            - SetPath=/api/car/{id}
        - id: car-service-post
          uri: ${CAR_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/car/{id}
            - Method=DELETE,OPTIONS
          filters:
            - SetPath=/api/car/{id}

